/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author Santoescu
 */
public class Factura extends javax.swing.JFrame {

    private Credito credi;
    private Contado cont;
    private int a;

    /**
     * Creates new form Factura
     */
    public Factura(Contado cont) {
        initComponents();
        
        this.cont = cont;

        setTitle("Factura No. " + cont.getnumventa());

        mostrarFacturaContado();
        this.setVisible(true);

        setResizable(false);
    }

    private void mostrarFacturaContado() {
        jTextArea1.append("\t              The OutletCity\n\t            NIT 1054924578\n\t              "+cont.getfecha()+"\n\nCodigo           Descipcion\tCantidad\tValor\tTotal\n------          ----------\t-------\t-----\t------\n" + productosContado()
                + "\nTipo\tCompra No.\tSubtotal\tInteres\tTotal\n-------\t--------\t--------\t-------\t-------\nContado\t" + cont.getnumventa() + "\t" + cont.total() + "\t0.0\t" + cont.total()
                +"\n\nCliente\t\tCedula\t\tTelefono\n-------\t\t------\t\t--------\n"+cont.getCliente().getNombre()+"\t\t"+cont.getCliente().getCedula()+"\t\t"+cont.getCliente().getTelefono()+
                "\n\nESTIMADO CLIENTE: EL PLAZO MAXIMO PARA REALIZAR DEVOLUCIONES\nO GARANTIA ES DE 30 DIAS, PARA MATERIALES DE OBRA 90 DIAS, ES\nINDESPENSABLE PRESENTAR ESTA FACTURA.");
    }
    private void mostrarFacturaCredito() {
        jTextArea1.append("\t              The OutletCity\n\t            NIT 1054924578\n\t              "+credi.getfecha()+"\n\nCodigo           Descipcion\tCantidad\tValor\tTotal\n------          ----------\t-------\t-----\t------\n" + productosCredito()
                + "\nTipo\tCompra No.\tSubtotal\tInteres\tTotal\n-------\t--------\t--------\t-------\t-------\nCredito\t" + credi.getnumventa() + "\t" + credi.total() + "\t"+credi.interes()+"\t" + credi.totalFinal()
                +"\n\nCuotas\tCliente\tCedula\tTelefono\n-------\t---------\t------\t--------\n"+credi.getCuotas()+"\t"+credi.getCliente().getNombre()+"\t"+credi.getCliente().getCedula()+"\t"+credi.getCliente().getTelefono()+
                "\n\nESTIMADO CLIENTE: EL PLAZO MAXIMO PARA REALIZAR DEVOLUCIONES\nO GARANTIA ES DE 30 DIAS, PARA MATERIALES DE OBRA 90 DIAS, ES\nINDESPENSABLE PRESENTAR ESTA FACTURA.");
    }

    private String productosCredito() {
        String s = "";
        for (int i = 0; i < credi.getPro().size(); i++) {
            s += String.valueOf(credi.getPro().get(i).getCodigo()) + "\t" + String.valueOf(credi.getPro().get(i).getNombre())
                    + "\t" + String.valueOf(credi.getPro().get(i).getCantidad()) + "\t" + String.valueOf(credi.getPro().get(i).getValor()) 
                    + "\t" + credi.getPro().get(i).getValor() * credi.getPro().get(i).getCantidad() + "\n";

        }

        return s;
    }
    private String productosContado() {
        String s = "";
        for (int i = 0; i < cont.getPro().size(); i++) {
            s += String.valueOf(cont.getPro().get(i).getCodigo()) + "\t" + String.valueOf(cont.getPro().get(i).getNombre())
                    + "\t" + String.valueOf(cont.getPro().get(i).getCantidad()) + "\t" + String.valueOf(cont.getPro().get(i).getValor()) 
                    + "\t" + cont.getPro().get(i).getValor() * cont.getPro().get(i).getCantidad() + "\n";

        }

        return s;
    }
    public Factura(Credito credi){
        initComponents();
        
        this.credi=credi;
        
        setTitle("Factura No. " + credi.getnumventa());
        
            mostrarFacturaCredito();
            this.setVisible(true);
       
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
